"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LUSD_OVERRIDE_ADDRESS = exports.BLUSD_AMM_STAKING_ADDRESS = exports.BLUSD_AMM_ADDRESS = exports.BLUSD_TOKEN_ADDRESS = exports.CHICKEN_BOND_MANAGER_ADDRESS = exports.BOND_NFT_ADDRESS = void 0;
var addresses_json_1 = require("./addresses.json");
Object.defineProperty(exports, "BOND_NFT_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.BOND_NFT_ADDRESS; } });
Object.defineProperty(exports, "CHICKEN_BOND_MANAGER_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.CHICKEN_BOND_MANAGER_ADDRESS; } });
Object.defineProperty(exports, "BLUSD_TOKEN_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.BLUSD_TOKEN_ADDRESS; } });
Object.defineProperty(exports, "BLUSD_AMM_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.BLUSD_AMM_ADDRESS; } });
Object.defineProperty(exports, "BLUSD_AMM_STAKING_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.BLUSD_AMM_STAKING_ADDRESS; } });
Object.defineProperty(exports, "LUSD_OVERRIDE_ADDRESS", { enumerable: true, get: function () { return addresses_json_1.LUSD_OVERRIDE_ADDRESS; } });
