#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

[ -d output ] || ./init
git filter-repo --paths-from-file 1-included-paths --target output

cd output
git filter-repo --paths-from-file ../2-excluded-paths --invert-paths

# Set up origin and tracking information for pushing to the public repo
git remote add origin git@github.com:liquity/liquity.git
git fetch
git branch -u origin/master
